import qbs.FileInfo

QtApplication {
    Depends { name: "Qt.widgets" }
    Depends { name: "Qt.network" }
    Depends { name: "Qt.charts" }
    Depends { name: "Qt.multimedia" }
    Depends { name: "Qt.multimediawidgets" }

    cpp.defines: [
        // You can make your code fail to compile if it uses deprecated APIs.
        // In order to do so, uncomment the following line.
        //"QT_DISABLE_DEPRECATED_BEFORE=0x060000" // disables all the APIs deprecated before Qt 6.0.0
    ]

    files: [
        "LICENSE",
        "QSourceHighlite/LICENSE",
        "QSourceHighlite/languagedata.cpp",
        "QSourceHighlite/languagedata.h",
        "QSourceHighlite/qsourcehighliter.cpp",
        "QSourceHighlite/qsourcehighliter.h",
        "QSourceHighlite/qsourcehighliterthemes.cpp",
        "QSourceHighlite/qsourcehighliterthemes.h",
        "QVariableSytleSheet/qvariablestylesheet.cpp",
        "QVariableSytleSheet/qvariablestylesheet.h",
        "README.md",
        "Resources.qrc",
        "data/klipper_commands.json",
        "main.cpp",
        "mainwindow.cpp",
        "mainwindow.h",
        "mainwindow.ui",
        "FLO_en_US.ts",
        "pages/dashboard/dashboardpage.cpp",
        "pages/dashboard/dashboardpage.h",
        "pages/dashboard/dashboardpage.ui",
        "pages/dashboard/widgets/printer/printerwidget.cpp",
        "pages/dashboard/widgets/printer/printerwidget.h",
        "pages/dashboard/widgets/printer/printerwidget.ui",
        "pages/dashboard/widgets/status/energy/energyconsumptionwidget.cpp",
        "pages/dashboard/widgets/status/energy/energyconsumptionwidget.h",
        "pages/dashboard/widgets/status/issue/issuelistitem.cpp",
        "pages/dashboard/widgets/status/issue/issuelistitem.h",
        "pages/dashboard/widgets/status/issue/issuelistwidget.cpp",
        "pages/dashboard/widgets/status/issue/issuelistwidget.h",
        "pages/dashboard/widgets/status/job/printjoblistitem.cpp",
        "pages/dashboard/widgets/status/job/printjoblistitem.h",
        "pages/dashboard/widgets/status/job/printjoblistwidget.cpp",
        "pages/dashboard/widgets/status/job/printjoblistwidget.h",
        "pages/dashboard/widgets/status/statuswidget.cpp",
        "pages/dashboard/widgets/status/statuswidget.h",
        "pages/dashboard/widgets/system/systemwidget.cpp",
        "pages/dashboard/widgets/system/systemwidget.h",
        "pages/dashboard/widgets/system/systemwidget.ui",
        "pages/loading/loadingpage.cpp",
        "pages/loading/loadingpage.h",
        "pages/loading/loadingpage.ui",
        "pages/printer/bedmesh/bedmeshwidget.cpp",
        "pages/printer/bedmesh/bedmeshwidget.h",
        "pages/printer/bedmesh/geometryengine.cpp",
        "pages/printer/bedmesh/geometryengine.h",
        "pages/printer/filebrowser/editor/fileeditor.cpp",
        "pages/printer/filebrowser/editor/fileeditor.h",
        "pages/printer/filebrowser/editor/fileeditor.ui",
        "pages/printer/filebrowser/filebrowser.cpp",
        "pages/printer/filebrowser/filebrowser.h",
        "pages/printer/filebrowser/filebrowseritem.cpp",
        "pages/printer/filebrowser/filebrowseritem.h",
        "pages/printer/filebrowser/filebrowserwidget.cpp",
        "pages/printer/filebrowser/filebrowserwidget.h",
        "pages/printer/filebrowser/overlay/filebrowseroverlay.cpp",
        "pages/printer/filebrowser/overlay/filebrowseroverlay.h",
        "pages/printer/offline/printerofflinescreen.cpp",
        "pages/printer/offline/printerofflinescreen.h",
        "pages/printer/offline/printerofflinescreen.ui",
        "pages/printer/printerpage.cpp",
        "pages/printer/printerpage.h",
        "pages/printer/printerpage.ui",
        "pages/printer/terminal/printerterminal.cpp",
        "pages/printer/terminal/printerterminal.h",
        "pages/printer/terminal/printerterminalitem.cpp",
        "pages/printer/terminal/printerterminalitem.h",
        "pages/printer/terminal/printerterminalwidget.cpp",
        "pages/printer/terminal/printerterminalwidget.h",
        "pages/printer/widgets/extruder/extruderwidget.cpp",
        "pages/printer/widgets/extruder/extruderwidget.h",
        "pages/printer/widgets/extruder/extruderwidget.ui",
        "pages/printer/widgets/printerbed/adjustment/adjustmentscrewframe.cpp",
        "pages/printer/widgets/printerbed/adjustment/adjustmentscrewframe.h",
        "pages/printer/widgets/printerbed/adjustment/adjustmentscrewframe.ui",
        "pages/printer/widgets/printerbed/adjustment/empty/adjustmentscrewemptyframe.cpp",
        "pages/printer/widgets/printerbed/adjustment/empty/adjustmentscrewemptyframe.h",
        "pages/printer/widgets/printerbed/adjustment/empty/adjustmentscrewemptyframe.ui",
        "pages/printer/widgets/printerbed/adjustment/item/adjustmentscrewitemframe.cpp",
        "pages/printer/widgets/printerbed/adjustment/item/adjustmentscrewitemframe.h",
        "pages/printer/widgets/printerbed/adjustment/item/adjustmentscrewitemframe.ui",
        "pages/printer/widgets/printerbed/bedmesh/bedmeshframe.cpp",
        "pages/printer/widgets/printerbed/bedmesh/bedmeshframe.h",
        "pages/printer/widgets/printerbed/bedmesh/bedmeshframe.ui",
        "pages/printer/widgets/printerbed/bedmesh/empty/bedmeshemptyframe.cpp",
        "pages/printer/widgets/printerbed/bedmesh/empty/bedmeshemptyframe.h",
        "pages/printer/widgets/printerbed/bedmesh/empty/bedmeshemptyframe.ui",
        "pages/printer/widgets/printerbed/bedmesh/item/bedmeshitemframe.cpp",
        "pages/printer/widgets/printerbed/bedmesh/item/bedmeshitemframe.h",
        "pages/printer/widgets/printerbed/bedmesh/item/bedmeshitemframe.ui",
        "pages/printer/widgets/printerbed/printerbedwidget.cpp",
        "pages/printer/widgets/printerbed/printerbedwidget.h",
        "pages/printer/widgets/printerbed/printerbedwidget.ui",
        "pages/printer/widgets/printerfan/printerfanwidget.cpp",
        "pages/printer/widgets/printerfan/printerfanwidget.h",
        "pages/printer/widgets/printerwebcam/empty/emptyprinterwebcamframe.cpp",
        "pages/printer/widgets/printerwebcam/empty/emptyprinterwebcamframe.h",
        "pages/printer/widgets/printerwebcam/printerwebcamwidget.cpp",
        "pages/printer/widgets/printerwebcam/printerwebcamwidget.h",
        "pages/settings/add_printer/addbedpage.cpp",
        "pages/settings/add_printer/addbedpage.h",
        "pages/settings/add_printer/addbedpage.ui",
        "pages/settings/add_printer/addextruderspage.cpp",
        "pages/settings/add_printer/addextruderspage.h",
        "pages/settings/add_printer/addextruderspage.ui",
        "pages/settings/add_printer/addprinterpage.cpp",
        "pages/settings/add_printer/addprinterpage.h",
        "pages/settings/add_printer/addprinterpage.ui",
        "pages/settings/add_printer/addprinterwizard.cpp",
        "pages/settings/add_printer/addprinterwizard.h",
        "pages/settings/add_printer/addprinterwizard.ui",
        "pages/settings/add_printer/validateprinterpage.cpp",
        "pages/settings/add_printer/validateprinterpage.h",
        "pages/settings/add_printer/validateprinterpage.ui",
        "pages/settings/edit_printer/editprinterdialog.cpp",
        "pages/settings/edit_printer/editprinterdialog.h",
        "pages/settings/edit_printer/editprinterdialog.ui",
        "pages/settings/edit_printer/qmoonrakervalidator.cpp",
        "pages/settings/edit_printer/qmoonrakervalidator.h",
        "pages/settings/printerlistitem.cpp",
        "pages/settings/printerlistitem.h",
        "pages/settings/printerlistitem.ui",
        "pages/settings/printerlistwidget.cpp",
        "pages/settings/printerlistwidget.h",
        "pages/settings/printerlistwidget.ui",
        "pages/settings/settingspage.cpp",
        "pages/settings/settingspage.h",
        "pages/settings/settingspage.ui",
        "pages/settings/theme/themesettingspage.cpp",
        "pages/settings/theme/themesettingspage.h",
        "pages/settings/theme/themesettingspage.ui",
        "shaders.qrc",
        "system/flo.cpp",
        "system/flo.h",
        "system/printerpool.cpp",
        "system/printerpool.h",
        "system/settings.cpp",
        "system/settings.h",
        "textures.qrc",
        "types/bed.cpp",
        "types/bed.h",
        "types/chamber.cpp",
        "types/chamber.h",
        "types/clientidentifier.cpp",
        "types/clientidentifier.h",
        "types/console/qabstractklipperconsole.cpp",
        "types/console/qabstractklipperconsole.h",
        "types/console/qlocalklipperconsole.cpp",
        "types/console/qlocalklipperconsole.h",
        "types/endstopstatus.cpp",
        "types/endstopstatus.h",
        "types/extruder.cpp",
        "types/extruder.h",
        "types/fan.cpp",
        "types/fan.h",
        "types/gcode/qgcodecommand.h",
        "types/gcode/qgcodemacro.h",
        "types/gcode/qgcodemove.h",
        "types/gcode/qgcodestore.h",
        "types/klipperfile.cpp",
        "types/klipperfile.h",
        "types/klippermessage.cpp",
        "types/klippermessage.h",
        "types/klipperresponse.cpp",
        "types/klipperresponse.h",
        "types/position.cpp",
        "types/position.h",
        "types/printer.cpp",
        "types/printer.h",
        "types/printerdefinition.h",
        "types/printjob.cpp",
        "types/printjob.h",
        "types/qsteppermotor.cpp",
        "types/qsteppermotor.h",
        "types/system.cpp",
        "types/system.h",
        "types/temperaturestore.h",
        "types/toolhead.cpp",
        "types/toolhead.h",
        "ui/circularprogressbar.cpp",
        "ui/circularprogressbar.h",
        "ui/layouts/qflowlayout.cpp",
        "ui/layouts/qflowlayout.h",
        "ui/list/qanimatedemptylistitem.cpp",
        "ui/list/qanimatedemptylistitem.h",
        "ui/list/qanimatedlistitem.cpp",
        "ui/list/qanimatedlistitem.h",
        "ui/list/qanimatedlistwidget.cpp",
        "ui/list/qanimatedlistwidget.h",
        "ui/menubutton.cpp",
        "ui/menubutton.h",
        "ui/menubutton.ui",
        "ui/popup.cpp",
        "ui/popup.h",
        "ui/popup.ui",
        "ui/qanimatedwidget.cpp",
        "ui/qanimatedwidget.h",
        "ui/qwebcamframe.cpp",
        "ui/qwebcamframe.h",
        "ui/qwidgetanimation.cpp",
        "ui/qwidgetanimation.h",
        "ui/widgetanimation.cpp",
        "ui/widgetanimation.h",
    ]

    Group {
        fileTagsFilter: "qm"
        Qt.core.resourcePrefix: "/i18n"
        fileTags: "qt.core.resource_data"
    }

    install: true
    installDir: qbs.targetOS.contains("qnx") ? FileInfo.joinPaths("/tmp", name, "bin") : base
}
